# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=password_not_1

# Expose SQL Server port
EXPOSE 1433

# Set the default command to run SQL Server
CMD ["/opt/mssql/bin/sqlservr"]
