version: '3.8'

services:
  sqlserver:
    build:
      context: .
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password_not_1"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
